### ISSUE TITLE
MethodTimer.dll required for Sitecore 8.2

### ISSUE THREAD

**Issue by richdman** [kamsar/Synthesis#33] opened 2016-09-03 18:36 UTC
`[FileNotFoundException: Could not load file or assembly 'MethodTimer, Version=1.15.10.0, Culture=neutral, PublicKeyToken=cb1364609f40a1dc' or one of its dependencies. The system cannot find the file specified.]
   System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type) +0
   System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext) +191
   System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) +162
   System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg) +148
   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent) +604
   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit) +212
   Synthesis.Utility.TypeCollectionUtility.WithAttribute(IEnumerable`1 types) in C:\Web\Synthesis\Source\Synthesis\Utility\TypeCollectionUtility.cs:23
   Synthesis.Synchronization.SynchronizationEngine.get_ModelDictionary() in C:\Web\Synthesis\Source\Synthesis\Synchronization\SynchronizationEngine.cs:119
   Synthesis.Synchronization.SynchronizationEngine.AreTemplatesSynchronized() in C:\Web\Synthesis\Source\Synthesis\Synchronization\SynchronizationEngine.cs:90
   Synthesis.<>c__DisplayClass1_0.<CheckSyncAll>b__0(IProviderConfiguration configuration, TemplateGenerationMetadata metadata) in C:\Web\Synthesis\Source\Synthesis\SynthesisHelper.cs:36
   Synthesis.SynthesisHelper.ExecMetadataWithAutoFriending(IEnumerable`1 configurations, Action`2 processAction) in C:\Web\Synthesis\Source\Synthesis\SynthesisHelper.cs:63`

**Comment by mrickmann** [comment] 2016-09-13 23:29
I am having the same issue. Anyone find a fix for this yet?

**Comment by kamsar** [comment] 2016-09-20 23:58
Are you using Sitecore.Glimpse? https://github.com/kevinobee/Sitecore.Glimpse/issues/37

**Comment by kamsar** [comment] 2016-09-21 00:00
This appears to be looking for https://github.com/Fody/MethodTimer? Certainly not something referenced by Synthesis, but if you were using Fody, it could be wrapping calls to time them.

**Comment by pveller** [comment] 2016-09-21 00:50
@kevinobee is a big fan of Fody. Hasn't seen it in Ship so you are probably spot on suspecting Glimpse :)

**Comment by kevinobee** [comment] 2016-09-21 15:43
I suspect Sitecore.Glimpse too, I will look into it for you, my apologies.

**Comment by mrickmann** [comment] 2016-09-21 16:04
We are not using Sitecore.Glimpse but received this same error after upgrading to Sitecore 8.2. I had to download the Synthesis source code and add a try catch around the foreach on line 23 of Synthesis.Utility.TypeCollectionUtility to get past the error. We are able to regenerate the model now, but it always says it's out of sync even after regenerating and compiling.

**Comment by kamsar** [comment] 2016-09-22 04:42
@mrickmann it sounds like you have something else that has a Fody dependency, direct or otherwise. If something is using Fody to wrap your methods in a timer then that could certainly explain having your models fail to display as synced - if the types that would make the sync complete are those throwing the error.

I am using Synthesis on a couple of 8.2 projects and so far I haven't had any issues. I did just commit some changes to the source to have it build against framework 4.5.2, which may well help the issue as well (several modules such as Unicorn and SPE have seen weird errors until that change with 8.2 - but nothing related to Fody)

**Comment by mrickmann** [comment] 2016-09-22 15:21
We have several other modules installed, including WFFM, so there very well could be a reference to it in one of those, but nothing direct. And odd that we didn't have this problem until after upgrading, that's why I was assuming it had something to do with Sitecore 8.2. I will get latest and build again and see if that helps. Thanks!

**Comment by smithc** [comment] 2016-10-12 15:10
Hey All,

I just stumbled upon this trying to solve the same issue, but without actually using Synthesis.

Turns out, this is an issue in Sitecore.  The type "Sitecore.Mvc.Pipelines.Loader.InitializeDependencyResolver" has been annotated with the [Time] attribute from MethodTimer in Fody, and because Sitecore doesn't ship that assembly, it's failing to load at runtime during resolution of the type's custom attributes.

I'm opening up a ticket with Sitecore support, but I thought I'd mention it here since you all seem to be running into it too.

**Comment by kamsar** [comment] 2016-10-12 17:58
Thanks for the note @smithc :)

**Comment by pankajj** [comment] 2016-10-18 15:29
I'm also running into same issue with Sitecore 8.2. @smithc does it make sense to just drop that dll in the /bin for now?

**Comment by smithc** [comment] 2016-10-18 15:33
Yes, dropping the MethodTimer dll into the bin folder should suffice as a temporary workaround until Sitecore fixes the issue in a subsequent update.

**Comment by WizX20** [comment] 2016-10-18 20:16
Is this by any chance [github.com/Fody/MethodTimer](https://github.com/Fody/MethodTimer)? If so, there is a NuGet available for that.

**Comment by kamsar** [comment] 2016-10-18 20:24
Yes it is that. And as @smithc says, dropping the NuGet or dll in the bin should provide a temporary workaround until Sitecore issues a fix. Right @kevinobee? 😀

**Comment by pankajj** [comment] 2016-10-18 20:39
anyone else using Sitecore 8.2 with their own implementation of DI (like Autofac)? I referenced this article: http://structuredcode.com/replacing-default-di-container-sitecore-8-2/ but still running into issues: 'Recursive upgradeable lock acquisitions not allowed in this mode.'

`Server Error in '/' Application.

Recursive upgradeable lock acquisitions not allowed in this mode.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Threading.LockRecursionException: Recursive upgradeable lock acquisitions not allowed in this mode.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[LockRecursionException: Recursive upgradeable lock acquisitions not allowed in this mode.]
   System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore(TimeoutTracker timeout) +3839391
   System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLock(TimeoutTracker timeout) +45
   Sitecore.Threading.Locks.UpgradeableReadScope..ctor(ReaderWriterLockSlim mutex) +107
   Sitecore.DependencyInjection.ServiceLocator.get_ServiceProvider() +85
   Sitecore.Sites.SiteContextFactory.<.cctor>b__0() +9
   System.Lazy`1.CreateValue() +244
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +31
   System.Lazy`1.get_Value() +14360453
   Sitecore.Sites.SiteContextFactory.GetSiteContext(String hostName, String fullPath, Int32 portNumber) +78
   Sitecore.Pipelines.HttpRequest.SiteResolver.ResolveSiteContext(HttpRequestArgs args) +430
   Sitecore.Pipelines.HttpRequest.SiteResolver.Process(HttpRequestArgs args) +50
   (Object , Object[] ) +74
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) +532
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +142
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92`

**Comment by smithc** [comment] 2016-10-18 20:44
Yes, it's funny you mention that.  We can take this off this thread if you like, but I've actually run into that integrating Autofac with Sitecore 8.2.  The issue is that the ServiceProviderBuilder must be fully initialized before you do anything else.  Now that most/many of the Sitecore services are requested from the ServiceProvider, you'll run into a chicken & the egg problem if you attempt to use Sitecore services within your ServiceProviderBuilder code.

I can't quite tell from the stacktrace you provided if you're the one doing it, but this includes running things like Sitecore pipelines.

If you're interested, I'm actually going to be presenting on some of this stuff during the [Sitecore User Group meeting in November](https://www.meetup.com/Sitecore-User-Group-New-England/events/234482940/).

**Comment by kamsar** [comment] 2016-10-18 21:00
Yep you can't use factory.createobject, for example, until the whole thing
is initialized.

**Comment by pankajj** [comment] 2016-10-19 14:22
@smithc it would be great if you can provide some insight on this. I wish I can come to the Nov meetup, but I will be on vaca and out of the country :(

Here is my IoCBuilder looks like: https://codeshare.io/57oTR and running into Line 10. 

The type or namespace ServicesModule could not be found error.

**Comment by kamsar** [comment] 2016-10-19 15:57
Closing this one. Not a bug in Synthesis.

**Closed by kamsar** 2016-10-19 15:57 UTC
Labels: bug, wontfix

**Comment by kamsar** [comment] 2016-12-05 14:36
This has been [fixed in 8.2 Update-1](https://dev.sitecore.net/Downloads/Sitecore%20Experience%20Platform/82/Sitecore%20Experience%20Platform%2082%20Update1/Release%20Notes):

> The following error appears in the log file during an upgrade: "...Could not load file or assembly 'MethodTimer, Version=1.15.10.0..".

**Comment by pankajj** [comment] 2016-12-05 14:56
Thanks for update.
