### ISSUE TITLE
Synthesis hangs when escaping from the webroot

### ISSUE THREAD

**Issue by mulate** [kamsar/Synthesis#26] opened 2015-10-28 17:44 UTC
Hey there.

I found an issue that when the path for the generated models is defined escaping from the webroot (e.g. "~/../something), the model generation hangs. If I change the path to be inside the webroot, everything works well.

**Comment by kamsar** [comment] 2015-10-28 17:46
That's odd. I'm working on a project right now that has `~/../Foo.Core/Model/_Interfaces.cs` for the output path.

This is the code that it uses to resolve the path:

     if (configPath.StartsWith("~"))
			{
				return System.Web.Hosting.HostingEnvironment.MapPath("~/") + configPath.Substring(1);
			}

			return configPath;

**Comment by mulate** [comment] 2015-10-28 18:02
I've been trying to see if it's something to do with permissions, but haven't found anything so far.

**Comment by kamsar** [comment] 2015-10-28 18:03
The IIS app pool user will need modify rights to the destination, but I'd expect an access denied error instead of a hang. Anything in the logs?

**Comment by mulate** [comment] 2015-10-28 18:30
Update on this... escaping from webroot one level works for me, my initial problem is with two levels (e.g. ~/../../something). Just tried it and it hanged. The process finishes correctly according to the log (and the model looks ok) but the /synthesis.aspx never comes back.

**Comment by andyshokry** [comment] 2015-11-06 22:29
Hey Kam,

We've identified the issue here. It looks like when we used multiple configurations, we explicitly hardcoded the location for model and interface generation, which has been fixed now.

The problem we're facing now is that since we're using multiple configurations, Synthesis does not seem to be able to rename model and interface files to generate new ones like it does with default install.

Any pointers?

**Comment by andyshokry** [comment] 2015-11-06 22:59
Ahhhh!!! Found the solution.

The problem is caused by "if (i == maxBackups && instanceExists)".

So now my parameters in BaseSiteModelConfiguration.cs look like this:

            // Parameters begin as a copy of what's in global config (e.g. base classes, etc)
            var parameters = (ConfigurationGeneratorParametersProvider)base.LoadGeneratorParametersProviderFromConfig();

            parameters.InterfaceNamespace = string.Format("{0}.Models", siteIdentifier);
            parameters.InterfaceOutputPath = string.Format("{0}{1}.Models.cs", interfaceOutputPath, siteIdentifier);
            parameters.ItemNamespace = string.Format("{0}.Models.Concrete", siteIdentifier);
            parameters.ItemOutputPath = string.Format("{0}{1}.Models.Concrete.cs", itemOutputPath, siteIdentifier);
            parameters.MaxBackupCopies = 5;

**Comment by kamsar** [comment] 2016-06-04 04:32
If I'm understanding this correctly it's caused by the same underlying issue as #28 - previously setting backups to zero would result in an infinite loop. In this case it looks like @andyshokry was just not setting the value, leaving it as `default(uint)` - which would be zero.

Since #28 will be fixed in the next release, I am marking this pending fix as well.

**Comment by kamsar** [comment] 2016-06-21 13:43
Fixed in 8.2.1

**Closed by kamsar** 2016-06-21 13:43 UTC
Labels: pending-fix
